### ISSUE TITLE
Code for Executing Uniform sampling is not available.

### ISSUE THREAD

**Issue by iamgmujtaba** [verlab/2019-sibgrapi-hyperlapse#1]
Hi There,

Thank you for your amazing tutorial. 

uniform_sampling.py is not available in [Uniform sampling](https://github.com/verlab/2019-sibgrapi-hyperlapse/blob/master/instructions/uniform.md) code.

Where can I get this file?

Thanks,

**Comment by michelmelosilva** [comment]
Hello Mujtaba.

Thank you for pointing this out. Actually, there was an error in the path to the file uniform_sampling.py. In fact, this file is in the folder src/.

I just updated the readme.md file with the corrected path.
Let me know if the it is ok for you now.

**Comment by iamgmujtaba** [comment]
Dear Michel, 

Thank you for updating the readme file. Sure I will update you if I find/get any error during execution.
